# For details of what checks are run for PRs please refer below
# docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Node CI

on:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: >
      test
      node${{ matrix.node-version }}
      ${{ matrix.os }}
      ${{ (matrix.experimental == true) && '[experimental]' || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          ## action based on https://github.com/actions/node-versions/releases
          ## see also: https://nodejs.org/en/about/releases/
          - "25"      # Current
          - '24'      # LTS
          - '22'
          - '20'
          - "20.18.0" # lowest supported
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        include:
          - node-version: "25"
            experimental: true
    timeout-minutes: 15
    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        # see https://github.com/actions/setup-node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup yarn
        run: |
          npm uninstall -g yarn
          corepack enable yarn
      - name: show node version
        run: node --version
      - name: show yarn version
        run: yarn --version
      - name: Setup subject
        run: yarn install --immutable
      - name: run tests
        run: yarn run test
